server:
  port: ${PORT:8088}
  error:
    include-message: always

spring:
  application:
    name: api-order-service
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:api_order}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        show_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization:
  output:
    ansi:
      enabled: Always
  sql:
    init:
      mode: always  #colocado para subir data.sql

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

api:
  url:
    api-food: ${API_FOOD_URL:http://localhost:8088}
    api-payment: ${API_PAYMENT_URL:http://localhost:8090}

environment:
  name: ${ENVIRONMENT:local}