apiVersion: v1
kind: Service
metadata:
  name: api-order-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: api-order-service
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
    - port: 89
      targetPort: 8089
      nodePort: 30008
  selector:
    app: api-order
